"""add agent_user table

Revision ID: 2470af8f5ed4
Revises: 
Create Date: 2026-07-24 18:34:29.092998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2470af8f5ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_user_username'), ['username'], unique=True)

    op.create_table('commission_period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('total_agents', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_label')
    )
    op.create_table('cordoba_chargeback_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('period_label', sa.String(length=10), nullable=False),
    sa.Column('assigned_company', sa.String(length=255), nullable=True),
    sa.Column('enrolled_date', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('marketing_payout_debt', sa.Float(), nullable=True),
    sa.Column('first_payment_cleared_date', sa.String(length=50), nullable=True),
    sa.Column('pay_freq', sa.String(length=50), nullable=True),
    sa.Column('payments_made', sa.Integer(), nullable=True),
    sa.Column('marketing_payment_cleared', sa.String(length=50), nullable=True),
    sa.Column('marketing_payment_chargeback', sa.String(length=50), nullable=True),
    sa.Column('file_dropped_date', sa.String(length=50), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cordoba_chargeback_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cordoba_chargeback_entry_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_cordoba_chargeback_entry_crm_id'), ['crm_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_cordoba_chargeback_entry_period_label'), ['period_label'], unique=False)

    op.create_table('cordoba_chargeback_matched_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cordoba_chargeback_matched_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cordoba_chargeback_matched_client_crm_id'), ['crm_id'], unique=True)

    op.create_table('cordoba_charged_back_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('clawback_amount', sa.Float(), nullable=True),
    sa.Column('dropped_period', sa.String(length=10), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cordoba_charged_back_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cordoba_charged_back_client_crm_id'), ['crm_id'], unique=True)

    op.create_table('cordoba_paid_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm_id', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cordoba_paid_client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cordoba_paid_client_crm_id'), ['crm_id'], unique=True)

    op.create_table('agent_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('units_cleared', sa.Integer(), nullable=False),
    sa.Column('total_cleared_debt', sa.Float(), nullable=False),
    sa.Column('cancellation_rate', sa.Float(), nullable=False),
    sa.Column('hourly_draw', sa.Float(), nullable=False),
    sa.Column('raw_tier', sa.Integer(), nullable=False),
    sa.Column('adjusted_tier', sa.Integer(), nullable=False),
    sa.Column('tier_rate', sa.Float(), nullable=False),
    sa.Column('gross_commission', sa.Float(), nullable=False),
    sa.Column('clawback_amount', sa.Float(), nullable=True),
    sa.Column('net_commission', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=False),
    sa.Column('payout_type', sa.String(length=20), nullable=False),
    sa.Column('quality_bonus_eligible', sa.Boolean(), nullable=True),
    sa.Column('cancellation_penalty_applied', sa.Boolean(), nullable=True),
    sa.Column('nsf_flagged', sa.Boolean(), nullable=True),
    sa.Column('pending_units', sa.Integer(), nullable=True),
    sa.Column('pending_debt', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['commission_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('agent_commission_id', sa.Integer(), nullable=True),
    sa.Column('crm_id', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('submitted_date', sa.String(length=50), nullable=True),
    sa.Column('enrolled_date', sa.String(length=50), nullable=True),
    sa.Column('first_payment_date', sa.String(length=50), nullable=True),
    sa.Column('first_payment_cleared_date', sa.String(length=50), nullable=True),
    sa.Column('second_payment_cleared_date', sa.String(length=50), nullable=True),
    sa.Column('dropped_date', sa.String(length=50), nullable=True),
    sa.Column('pay_freq', sa.String(length=50), nullable=True),
    sa.Column('payments_made', sa.Integer(), nullable=True),
    sa.Column('nsf_count', sa.Integer(), nullable=True),
    sa.Column('enrolled_debt', sa.Float(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('is_low_credit', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_cleared', sa.Boolean(), nullable=True),
    sa.Column('is_pending', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('commission_on_client', sa.Float(), nullable=True),
    sa.Column('clawback_applied', sa.Boolean(), nullable=True),
    sa.Column('clawback_period_id', sa.Integer(), nullable=True),
    sa.Column('clawback_amount', sa.Float(), nullable=True),
    sa.Column('is_late_activation', sa.Boolean(), nullable=True),
    sa.Column('original_cleared_period', sa.String(length=10), nullable=True),
    sa.Column('cordoba_paid', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['agent_commission_id'], ['agent_commission.id'], ),
    sa.ForeignKeyConstraint(['clawback_period_id'], ['commission_period.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['commission_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_record_agent_commission_id'), ['agent_commission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_record_crm_id'), ['crm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_record_period_id'), ['period_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_record_period_id'))
        batch_op.drop_index(batch_op.f('ix_client_record_crm_id'))
        batch_op.drop_index(batch_op.f('ix_client_record_agent_commission_id'))

    op.drop_table('client_record')
    op.drop_table('agent_commission')
    with op.batch_alter_table('cordoba_paid_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cordoba_paid_client_crm_id'))

    op.drop_table('cordoba_paid_client')
    with op.batch_alter_table('cordoba_charged_back_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cordoba_charged_back_client_crm_id'))

    op.drop_table('cordoba_charged_back_client')
    with op.batch_alter_table('cordoba_chargeback_matched_client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cordoba_chargeback_matched_client_crm_id'))

    op.drop_table('cordoba_chargeback_matched_client')
    with op.batch_alter_table('cordoba_chargeback_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cordoba_chargeback_entry_period_label'))
        batch_op.drop_index(batch_op.f('ix_cordoba_chargeback_entry_crm_id'))
        batch_op.drop_index(batch_op.f('ix_cordoba_chargeback_entry_agent_name'))

    op.drop_table('cordoba_chargeback_entry')
    op.drop_table('commission_period')
    with op.batch_alter_table('agent_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_user_username'))

    op.drop_table('agent_user')
    # ### end Alembic commands ###
